### ISSUE TITLE
connectDragSource not working

### ISSUE THREAD

**Issue by caraie** [cormacrelf/angular-skyhook#318] opened 2019-03-16 19:37 UTC
Hi,
I'm trying to use connectDragSource instead of the DragSource directive and connectDropTarget instead of the DropTarget directive.

Using the example here: 
https://github.com/cormacrelf/angular-skyhook/tree/master/packages/examples/src/app/basic-sortable/

I successfuly connected the target using the connectDropTarget by doing this:
```
    ngAfterViewInit() {
        if (this.elRef) {
            this.cardTarget.connectDropTarget(this.elRef.nativeElement);
        }
    }
```
and removing the dropTarget directive from the template and the example still works fine.

But when doing the same with the source the example stop working, I'm not able to drag and drop anything.

```
    ngAfterViewInit() {
        if (this.elRef) {
            this.cardTarget.connectDropTarget(this.elRef.nativeElement);
            this.cardSource.connectDragSource(this.elRef.nativeElement); // this doesn't work
        }
    }
```

Any idea?
Thanks!

**Comment by cormacrelf** [comment] 2019-03-17 11:12
I don’t know, can you make a stackblitz out of it?

**Comment by cormacrelf** [comment] 2019-06-17 06:38
https://stackblitz.com/edit/angular-xngita?file=src%2Fapp%2Fapp.component.ts

Closing because I cannot reproduce. The only thing that I can think of is that maybe you didn't set a type on the drag source, which means it will forever defer connecting. Call `setType` to do this. The docs go into more detail on setType.

**Closed by cormacrelf** 2019-06-17 06:38 UTC
Labels: triage
